[programs.localnet]
credix_permissioned_market = "GuPsqCV7H2bw35UFBHvmzNgK28qVe92U5vq7JJigjPUv"
credix = "6i5vHpj1fVDqaWxknwH8mfCjkm2zZVwgDtfPMg19nzQK"

[programs.devnet]
credix_permissioned_market = "GuPsqCV7H2bw35UFBHvmzNgK28qVe92U5vq7JJigjPUv"
credix = "6i5vHpj1fVDqaWxknwH8mfCjkm2zZVwgDtfPMg19nzQK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*"

[[test.genesis]]
address = "6i5vHpj1fVDqaWxknwH8mfCjkm2zZVwgDtfPMg19nzQK"
program = "./target/deploy/credix.so"

[[test.genesis]]
address = "GuPsqCV7H2bw35UFBHvmzNgK28qVe92U5vq7JJigjPUv"
program = "./target/deploy/credix_permissioned_market.so"

[[test.genesis]]
address = "gatem74V238djXdzWnJf94Wo1DcnuGkfijbf3AuBhfs"
program = "./artifacts/solana_gateway_program.so"

[[test.genesis]]
address = "4sN8PnN2ki2W4TFXAfzR645FWs8nimmsYeNtxM8RBK6A"
program = "./artifacts/spl_token_faucet.so"

[[test.genesis]]
address = "A3KCE92wXZMtGGJT6XYL2KHva58VXvWkhcqfJ6Q5JEia"
program = "./artifacts/serum_dex.so"
