[programs.localnet]
credix_permissioned_market = "B82qssUC4qJT3DXohg8A1k6TuUBNcjnf5d4KX8uJmhDK"
credix = "D58Th9Y4tFssgZaCPQ6diJoiFC6TvcENsiYR6ZbRoosK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*"

[[test.genesis]]
address = "v1yuc1NDc1N1YBWGFdbGjEDBXepcbDeHY1NphTCgkAP"
program = "./target/deploy/credix.so"

[[test.genesis]]
address = "iPRL869bGrTiJZP6GW2ysPYXV9PMKSMAr6CYhRJx3zq"
program = "./target/deploy/credix_permissioned_market.so"

[[test.genesis]]
address = "gatem74V238djXdzWnJf94Wo1DcnuGkfijbf3AuBhfs"
program = "./artifacts/solana_gateway_program.so"

[[test.genesis]]
address = "4sN8PnN2ki2W4TFXAfzR645FWs8nimmsYeNtxM8RBK6A"
program = "./artifacts/spl_token_faucet.so"

[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "./artifacts/serum_dex.so"
